Issue152 css layout
hlxsites/24life pull request #159
Opened 2023-09-14 22:32 UTC by meejain

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #152 

Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/search?q=francisco
- After: https://issue152-css-layout--24life--hlxsites.hlx.live/search?q=francisco

2023-09-14 22:33 UTC, synox commented on scripts/lib-franklin.js
> +  console.log(shortBlockName);
Unexpected console statement

2023-09-14 22:34 UTC, synox commented on blocks/search-results/search-results.js
> +// eslint-disable-next-line
only disable specifically

2023-09-14 22:35 UTC, synox requested changes
This does not yet address the layout shift of #149

2023-09-15 00:29 UTC, synox commented on blocks/search-results/search-results.css
Please also set a clearer title for the PR, you can usually copy from the issue

2023-09-15 08:36 UTC, meejain commented on scripts/lib-franklin.js
> +  console.log(shortBlockName);
Fixed

2023-09-15 08:45 UTC, meejain commented on blocks/search-results/search-results.js
> +// eslint-disable-next-line
fixed

2023-09-15 12:30 UTC, meejain commented
After making the changes in the nav flex - we could see the change in the cumulative lay out shift

<img width="1467" alt="image" src="https://github.com/hlxsites/24life/assets/37831850/d104534a-f374-4279-901a-76c1a844639b">

2023-09-15 12:34 UTC, meejain commented
Further search queries - https://issue152-css-layout--24life--hlxsites.hlx.live/search?q=game+francisco
<img width="1461" alt="image" src="https://github.com/hlxsites/24life/assets/37831850/02ea3308-f5ed-49c4-85ef-0cebf6b861ca">

2023-09-19 23:46 UTC, synox approved these changes

2023-09-20 11:45 UTC, merged